### ISSUE TITLE
Question about using basicsr

### ISSUE THREAD

**Issue by junyizeng** [hejingwenhejingwen/GCFSR#17]
Thank you very much for your open-source contributions. I have successfully set up the Anaconda virtual environment as per the instructions in your README. However, I encountered an issue when trying to use BasicSR in inference_gcfsr_blind.py, and the error message is as follows:

Testing 0 XMY-176
Traceback (most recent call last):
  File "/media/cqnu/data/zjy/GCFSR-main/inference/inference_gcfsr_blind.py", line 70, in <module>
    main()
  File "/media/cqnu/data/zjy/GCFSR-main/inference/inference_gcfsr_blind.py", line 67, in main
    generate(args, img, model, device, imgname)
  File "/media/cqnu/data/zjy/GCFSR-main/inference/inference_gcfsr_blind.py", line 20, in generate
    output, _ = g_ema(img)
  File "/home/cqnu/anaconda3/envs/human-resolu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cqnu/anaconda3/envs/human-resolu/lib/python3.7/site-packages/basicsr/archs/gcfsr_arch.py", line 1089, in forward
    feat = self.conv_body_first(x)
  File "/home/cqnu/anaconda3/envs/human-resolu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cqnu/anaconda3/envs/human-resolu/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cqnu/anaconda3/envs/human-resolu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cqnu/anaconda3/envs/human-resolu/lib/python3.7/site-packages/basicsr/ops/fused_act/fused_act.py", line 90, in forward
    return fused_leaky_relu(input, self.bias, self.negative_slope, self.scale)
  File "/home/cqnu/anaconda3/envs/human-resolu/lib/python3.7/site-packages/basicsr/ops/fused_act/fused_act.py", line 94, in fused_leaky_relu
    return FusedLeakyReLUFunction.apply(input, bias, negative_slope, scale)
  File "/home/cqnu/anaconda3/envs/human-resolu/lib/python3.7/site-packages/basicsr/ops/fused_act/fused_act.py", line 64, in forward
    out = fused_act_ext.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale)
NameError: name 'fused_act_ext' is not defined

Could you please advise on how to address this issue? I look forward to your response.

**Comment by wzylove** [comment]
I have also encountered this problem. Is there something missing

**Comment by JHLGXFF** [comment]
I have also met this question.

**Comment by JHLGXFF** [comment]
https://github.com/TencentARC/GFPGAN/issues/5   try this way
