### ISSUE TITLE
How can I get the quantitative results such as PSNR, SSIM, LPIPS and FID?

### ISSUE THREAD

**Issue by dongfengxijian** [hejingwenhejingwen/GCFSR#5]
Thank you for your excellent work! When I train the GCFSR, I can't get the quantitative results such PSNR, SSIM, LPIPS and FID? How can I get it?
![微信图片_20220915105716](https://user-images.githubusercontent.com/24863806/190303335-35fd819e-c1c6-4d92-a289-80974e7aca5d.png)

**Comment by laihuitreg** [comment]
Hello, what content needs to be modified to train correctly as a beginner in deep learning?

**Comment by laihuitreg** [comment]
2023-04-24 16:03:57,402 INFO: Start training from epoch: 0, iter: 0 Traceback (most recent call last):
  File "basicsr/train.py", line 206, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 167, in train_pipeline
    model.optimize_parameters(current_iter)
  File "d:\models\gcfsr\basicsr\models\gcfsr_model.py", line 219, in optimize_parameters
    fake_img, _ = self.net_g(self.lq, self.in_size)
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\nn\parallel\distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\nn\parallel\distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\models\gcfsr\basicsr\archs\gcfsr_arch.py", line 918, in forward
    tmp = self.final_down2(self.final_down1(feat))
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\models\gcfsr\basicsr\archs\gcfsr_arch.py", line 440, in forward
    out = F.conv2d( RuntimeError: Calculated padded input size per channel: (2 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 14468) of binary: D:\Anaconda\envs\ptgpu\python.exe Traceback (most recent call last):
  File "D:\Anaconda\envs\ptgpu\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\envs\ptgpu\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\distributed\launch.py", line 193, in <module>
    main()
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\distributed\launch.py", line 189, in main
    launch(args)
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\distributed\launch.py", line 174, in launch
    run(args)
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\distributed\run.py", line 752, in run
    elastic_launch(
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\Anaconda\envs\ptgpu\lib\site-packages\torch\distributed\launcher\api.py", line 245, in launch_agent
    raise ChildFailedError( torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by laihuitreg** [comment]
The above is the problem I encountered

**Comment by dongfengxijian** [comment]
The convolution with kernel size of 3 while input features with size of 2.Maybe the input is smaller than the original data, or you modify the model.
