### ISSUE TITLE
Inference not working

### ISSUE THREAD

**Issue by netrunner-exe** [hejingwenhejingwen/GCFSR#9]
```
Testing 0 DSC00324_01
Traceback (most recent call last):
  File "inference_gcfsr_blind.py", line 69, in <module>
    main()
  File "inference_gcfsr_blind.py", line 66, in main
    generate(args, img, model, device, imgname)
  File "inference_gcfsr_blind.py", line 19, in generate
    output, _ = g_ema(img)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/GCFSR/basicsr/archs/gcfsr_arch.py", line 1120, in forward
    latent = self.final_linear(tmp.view(b, -1)).view(-1, self.num_latent, self.num_style_feat)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/GCFSR/basicsr/archs/gcfsr_arch.py", line 172, in forward
    out = F.linear(x, self.weight * self.scale)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x32768 and 8192x6144)
```

**Comment by morning12138** [comment]
I tried, and it worked when the picture size is 512 * 512. Otherwise it will not work.

**Comment by xiumin123** [comment]
Hello,I have met the same question,and  i have resized input image 512*512,do you solve the problem.
Traceback (most recent call last):
  File "/data01/zhangxiumin/codeyard/GCFSR-main/inference/inference_gcfsr.py", line 79, in <module>
    main()
  File "/data01/zhangxiumin/codeyard/GCFSR-main/inference/inference_gcfsr.py", line 76, in main
    generate(args, img, cond, model, device, imgname)
  File "/data01/zhangxiumin/codeyard/GCFSR-main/inference/inference_gcfsr.py", line 19, in generate
    output, _ = g_ema(img, cond)
  File "/home/zhangxiumin/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data01/zhangxiumin/codeyard/GCFSR-main/basicsr/archs/gcfsr_arch.py", line 919, in forward
    latent = self.final_linear(tmp.view(b, -1)).view(-1, self.num_latent, self.num_style_feat)
  File "/home/zhangxiumin/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data01/zhangxiumin/codeyard/GCFSR-main/basicsr/archs/gcfsr_arch.py", line 172, in forward
    out = F.linear(x, self.weight * self.scale)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1024 and 4096x7168)
